default:
  image: python:3.8

stages:
  - test
test:
  interruptible: false
  stage: test
  script:
    - bash -c 'wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"'
    - bash -c 'unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"'
    - mv terraform /usr/bin/
    - python test.py
