default:
  image: python:3.8

stages:
  - test
test:
  interruptible: false
  stage: test
  script:
    - wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
    - unzip terraform_0.12.18_linux_amd64.zip
    - mv terraform /usr/bin/
    - python test.py
